---

- name: Create swap file
  command: dd if=/dev/zero of={{ swap_file_path }} bs=1024 count={{ swap_file_size_mb }}k
           creates="{{ swap_file_path }}"
  register: swapcreated

- name: Change swap file permissions
  file: path="{{ swap_file_path }}" owner=root group=root mode=0600

- name: Make swap file
  command: mkswap {{ swap_file_path }}
  when: not swapcreated|skipped

- name: Write swap entry in fstab
  mount: name=none src={{ swap_file_path }} fstype=swap opts=sw passno=0 dump=0 state=present
  when: not swapcreated|skipped

- name: Mount swap
  command: swapon {{ swap_file_path }}
  when: not swapcreated|skipped
